services:
  postgres:
    image: postgres:17
    container_name: approval-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ApprovalWorkflowDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
     - "5433:5432"
    volumes:
      - approval-postgres-data:/var/lib/postgresql/data
volumes:
  approval-postgres-data:
